 
 //z_index omitted
 
 function start(){
	


var mainBG = document.createElement("Div");
    mainBG.class = "editPanel";
	mainBG.id = "main";
	
	var add = document.createElement("Button");
        add.class = "editPanel";
	    add.className = "tags btn";
        add.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/finance-and-business-set2/32/fin32px080-16.png")';
	mainBG.appendChild(add);
	
	var edit = document.createElement("Button");
        edit.class = "editPanel";
	    edit.className = "tags btn";
        edit.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/single-width-stroke/24/oui-icons-50-16.png")';
    mainBG.appendChild(edit);
    
	var dlt = document.createElement("Button");
        dlt.class = "editPanel";
	    dlt.className = "tags btn";
        dlt.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/streamline-icon-set-free-pack/48/Streamline-70-16.png")';
    mainBG.appendChild(dlt);
		   
    var space = document.createElement("Div");
        space.class = "editPanel";
        space.className = "space";
		
	mainBG.appendChild(space);
	
	
	var selector = document.createElement("Button");
	    selector.class = "editPanel";
        selector.className = "tags btn";
        selector.style.backgroundImage = 'url("https://cdn1.iconfinder.com/data/icons/line-essentials-84/20/4126-16.png")';
	mainBG.appendChild(selector);
	
	var space = document.createElement("Div");
        space.class = "editPanel";
        space.className = "space";
	mainBG.appendChild(space);
	
	var ancestors = new Array();
	    ancestors[0] = document.createElement("Label");
        ancestors[0].class = "editPanel";
        ancestors[0].className = "ancestors";
		var txt = document.createTextNode("helloooooooooooooooo");
		ancestors[0].appendChild(txt);
	mainBG.appendChild(ancestors[0]);
	    ancestors[1] = document.createElement("Label");
        ancestors[1].class = "editPanel";
        ancestors[1].className = "ancestors";
		var txt = document.createTextNode("helloooooooooooooooo");
		ancestors[1].appendChild(txt);
	mainBG.appendChild(ancestors[1]);
		ancestors[2] = document.createElement("Label");
        ancestors[2].class = "editPanel";
        ancestors[2].className = "ancestors";
		var txt = document.createTextNode("helloooooooooooooooo");
		ancestors[2].appendChild(txt);
	mainBG.appendChild(ancestors[2]);
	    ancestors[3] = document.createElement("Label");
        ancestors[3].class = "editPanel";
        ancestors[3].className = "ancestors";
		var txt = document.createTextNode("helloooooooooooooooo");
		ancestors[3].appendChild(txt);
	mainBG.appendChild(ancestors[3]);
	    ancestors[4] = document.createElement("Label");
        ancestors[4].class = "editPanel";
        ancestors[4].className = "ancestors";
		var txt = document.createTextNode("helloooooooooooooooo");
		ancestors[4].appendChild(txt);
	mainBG.appendChild(ancestors[4]);    
	
	var space = document.createElement("Div");
        space.class = "editPanel";
        space.className = "space";
		//space3.setAttribute("style","width:100px;");
	mainBG.appendChild(space);
	
	var close = document.createElement("Button");
        close.class = "editPanel";
	    close.className = " tags btn";
        close.style.backgroundImage = 'url("https://cdn0.iconfinder.com/data/icons/navigation-set-arrows-part-one/32/CloseCancelSquare-16.png")';
    mainBG.appendChild(close);

var htmlmenu = document.createElement("Div");
    htmlmenu.class = "editPanel";
	htmlmenu.className = "submenu";
		
	var text = document.createElement("Button");
	    text.class = "editPanel";
	    var txt = document.createTextNode("<text>");
		text.appendChild(txt);
	    text.className = "tags";
		text.style.marginLeft="2px";
	htmlmenu.appendChild(text);
	var button = document.createElement("Button");;
	    button.class = "editPanel";
	    var txt = document.createTextNode("<button>");
		button.appendChild(txt);
	    button.className = "tags";
	htmlmenu.appendChild(button);
	var label = document.createElement("Button");;
	    label.class = "editPanel";
	    var txt = document.createTextNode("<label>");
		label.appendChild(txt);
	    label.className = "tags";
	htmlmenu.appendChild(label);
	var div = document.createElement("Button");;
	    div.class = "editPanel";
	    var txt = document.createTextNode("<div>");
		div.appendChild(txt);
	    div.className = "tags";
	htmlmenu.appendChild(div);
	var span = document.createElement("Button");;
	    span.class = "editPanel";
	    var txt = document.createTextNode("<span>");
		span.appendChild(txt);
	    span.className = "tags";
	htmlmenu.appendChild(span);
	var link = document.createElement("Button");;
	    link.class = "editPanel";
	    var txt = document.createTextNode("<link>");
		link.appendChild(txt);
	    link.className = "tags";
	htmlmenu.appendChild(link);
	var input = document.createElement("select");
        input.class = "editPanel";
	    input.className = "tags";
	      var op = document.createElement("option");
	          op.text ="<input>";
	    input.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="Text";
	    input.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="Button";
	    input.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="checkbox";
	    input.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="color";
	    input.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="Date";
	    input.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="email";
	    input.appendChild(op6);
	      var op7 = document.createElement("option");
	          op7.text ="month";
	    input.appendChild(op7);
	      var op8 = document.createElement("option");
	          op8.text ="number";
	    input.appendChild(op8);
	      var op9 = document.createElement("option");
	          op9.text ="password";
	    input.appendChild(op9);
	      var op10 = document.createElement("option");
	          op10.text ="radio";
	    input.appendChild(op10);
	      var op11 = document.createElement("option");
	          op11.text ="range";
	    input.appendChild(op11);
	      var op12 = document.createElement("option");
	          op12.text ="reset";
	    input.appendChild(op12);
	      var op13 = document.createElement("option");
	          op13.text ="search";
	    input.appendChild(op13);
	      var op14 = document.createElement("option");
	          op14.text ="submit";
	    input.appendChild(op14);
	      var op15 = document.createElement("option");
	          op15.text ="tel";
	    input.appendChild(op15);
	      var op16 = document.createElement("option");
	          op16.text ="time";
	    input.appendChild(op16);
	      var op17 = document.createElement("option");
	          op17.text ="url";
	    input.appendChild(op17);
		
	htmlmenu.appendChild(input);
	
	//mainBG.appendChild(htmlmenu);
	 
var cssmenu = document.createElement("Div");
    cssmenu.class = "editPanel";
	cssmenu.className = "submenu";
	
	var width = document.createElement("select");
        width.class = "editPanel";
	    width.className = "tags";
        width.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/resize/256/resize-29-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    width.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="-100 ";
	    width.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="-50 ";
	    width.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="-25 ";
	    width.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="-10 ";
	    width.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="-5 ";
	    width.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="+5 ";
	    width.appendChild(op6);
	      var op7 = document.createElement("option");
	          op7.text ="+10 ";
	    width.appendChild(op7);
	      var op8 = document.createElement("option");
	          op8.text ="+25 ";
	    width.appendChild(op8);
	      var op9 = document.createElement("option");
	          op9.text ="+50 ";
	    width.appendChild(op9);	
		  var op10 = document.createElement("option");
	          op10.text ="+100 ";
	    width.appendChild(op10);
	    width.class = "editPanel";
	    width.className = "cssbtns";
    cssmenu.appendChild( width);
	
	var height = document.createElement("select");
        height.class = "editPanel";
	    height.className = "tags";
        height.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/resize/256/resize-30-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    height.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="-100 ";
	    height.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="-50 ";
	    height.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="-25 ";
	    height.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="-10 ";
	    height.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="-5 ";
	    height.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="+5 ";
	    height.appendChild(op6);
	      var op7 = document.createElement("option");
	          op7.text ="+10 ";
	    height.appendChild(op7);
	      var op8 = document.createElement("option");
	          op8.text ="+25 ";
	    height.appendChild(op8);
	      var op9 = document.createElement("option");
	          op9.text ="+50 ";
	    height.appendChild(op9);	
		  var op10 = document.createElement("option");
	          op10.text ="+100 ";
	    height.appendChild(op10);	    height.class = "editPanel";
	    height.className = "cssbtns";
    cssmenu.appendChild( height);
	
	var position = document.createElement("select");
        position.class = "editPanel";
	    position.className = "tags btn";
        position.style.backgroundImage = 'url("https://cdn1.iconfinder.com/data/icons/epic-hand-drawns/64/location_2-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    position.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="static";
	    position.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="relative";
	    position.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="absolute";
	    position.appendChild(op3);
	cssmenu.appendChild(position);
	
	var move = document.createElement("Button");
        move.class = "editPanel";
	    move.className = "tags btn";
        move.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/edition/100/move-16.png")';
	cssmenu.appendChild(move);
	
	
	var BGcolor = document.createElement("Label");
        BGcolor.class = "editPanel";
	    BGcolor.className = "tags inputs ";
        BGcolor.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/essentials-volume-6/128/color-wheel-16.png")';
		var picker = document.createElement("Input");
		    picker.class ="editPanel";
			picker.type ="color";
			picker.className = "color";
		BGcolor.appendChild(picker);
	cssmenu.appendChild(BGcolor);	

	var BGimg = document.createElement("Label");
        BGimg.class = "editPanel";
	    BGimg.className = "tags inputs";
        BGimg.style.backgroundImage = 'url("https://cdn2.iconfinder.com/data/icons/pittogrammi/142/32-16.png")';
		var file = document.createElement("Input");
		    file.class ="editPanel";
			file.type ="file";
			file.className ="file";
			file.accept="image/x-png,image/gif,image/jpeg"
		BGimg.appendChild(file);
	cssmenu.appendChild(BGimg);	

	var border = document.createElement("select");
        border.class = "editPanel";
	    border.className = "tags";
        border.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/glyph/227/Rectangular-1-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    border.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="none";
	    border.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="solid";
	    border.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="dashed";
	    border.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="dotted";
	    border.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="double";
	    border.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="groove";
	    border.appendChild(op6);
	      var op7 = document.createElement("option");
	          op7.text ="ridge";
	    border.appendChild(op7);
	      var op8 = document.createElement("option");
	          op8.text ="inset";
	    border.appendChild(op8);
	      var op9 = document.createElement("option");
	          op9.text ="outset";
	    border.appendChild(op9);	
	    border.class = "editPanel";
	    border.className = "cssbtns";
    cssmenu.appendChild( border);

    var borderleft = document.createElement("Button");
        borderleft.class = "editPanel";
	    borderleft.className = "tags btn";
        borderleft.style.backgroundImage = 'url("https://cdn1.iconfinder.com/data/icons/CrystalClear/16x16/actions/border_left.png")';
	cssmenu.appendChild(borderleft);	
	
    var borderright = document.createElement("Button");
        borderright.class = "editPanel";
	    borderright.className = "tags btn";
        borderright.style.backgroundImage = 'url("https://cdn2.iconfinder.com/data/icons/LinspireClear/16x16/actions/border_right.png")';
	cssmenu.appendChild(borderright);
	
    var bordertop = document.createElement("Button");
        bordertop.class = "editPanel";
	    bordertop.className = "tags btn";
        bordertop.style.backgroundImage = 'url("https://cdn1.iconfinder.com/data/icons/CrystalClear/16x16/actions/border_top.png")';
	cssmenu.appendChild(bordertop);
	
    var borderbottom = document.createElement("Button");
        borderbottom.class = "editPanel";
	    borderbottom.className = "tags btn";
        borderbottom.style.backgroundImage = 'url("https://cdn1.iconfinder.com/data/icons/CrystalClear/16x16/actions/border_bottom.png")';
	cssmenu.appendChild(borderbottom);	
    
	var borderwidth= document.createElement("select");
        borderwidth.class = "editPanel";
	    borderwidth.className = "tags";
        borderwidth.style.backgroundImage = 'url("https://cdn0.iconfinder.com/data/icons/penthemes-layour-builder/512/button-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    borderwidth.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="0.5";
	    borderwidth.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="1";
	    borderwidth.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="2";
	    borderwidth.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="4";
	    borderwidth.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="8";
	    borderwidth.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="10";
	    borderwidth.appendChild(op6);
	      var op7 = document.createElement("option");
	          op7.text ="12";
	    borderwidth.appendChild(op7);
	      var op8 = document.createElement("option");
	          op8.text ="16";
	    borderwidth.appendChild(op8);
	      var op9 = document.createElement("option");
	          op9.text ="20";
	    borderwidth.appendChild(op9);	
	    borderwidth.class = "editPanel";
	    borderwidth.className = "cssbtns";
    cssmenu.appendChild( borderwidth);
		var bordercolor = document.createElement("Label");
        bordercolor.class = "editPanel";
	    bordercolor.className = "tags inputs ";
        bordercolor.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/essentials-volume-6/128/color-wheel-16.png")';
		var picker = document.createElement("Input");
		    picker.class ="editPanel";
			picker.type ="color";
			picker.className = "color";
		bordercolor.appendChild(picker);
	cssmenu.appendChild(bordercolor);

	var newtxt = document.createElement("input");
        newtxt.class = "editPanel";
	    newtxt.className = "tags";
		newtxt.style.border ="1px solid black";
	cssmenu.appendChild(newtxt);
	var enter = document.createElement("Button");
        enter.class = "editPanel";
	    enter.className = "tags btn";
        enter.style.backgroundImage = 'url("https://cdn0.iconfinder.com/data/icons/arrows-of-ways/154/turn-16.png")';
	cssmenu.appendChild(enter);
	
    var font = document.createElement("select");
        font.class = "editPanel";
	    font.className = "tags";
        font.style.backgroundImage = 'url("https://cdn2.iconfinder.com/data/icons/font-awesome/1792/font-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    font.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="Arial";
			  op1.style.fontFamily ="Arial";
	    font.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="Georgia";
			  op2.style.fontFamily ="Georgia";
	    font.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="Impact";
			  op3.style.fontFamily ="Impact";
	    font.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="Tahoma";
			  op4.style.fontFamily ="Tahoma";
	    font.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="Times New Roman";
			  op5.style.fontFamily ="Times New Roman";
	    font.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="Verdana";
			  op6.style.fontFamily ="Verdana";
	    font.appendChild(op6);
	cssmenu.appendChild(font);	
		var txtsize = document.createElement("select");
        txtsize.class = "editPanel";
	    txtsize.className = "tags";
        txtsize.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/glypho-generic-icons/64/edit-font-size-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    txtsize.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="8";
	    txtsize.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="10";
	    txtsize.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="12";
	    txtsize.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="16";
	    txtsize.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="32";
	    txtsize.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="64";
	    txtsize.appendChild(op6);
    cssmenu.appendChild(txtsize);
	var bold = document.createElement("Button");
        bold.class = "editPanel";
	    bold.className = "tags btn";
        bold.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/glypho-generic-icons/64/edit-bold-16.png")';
	cssmenu.appendChild(bold);
	var italic = document.createElement("Button");
        italic.class = "editPanel";
	    italic.className = "tags btn";
        italic.style.backgroundImage = 'url("https://cdn1.iconfinder.com/data/icons/text-editor-4/1792/italic-16.png")';
	cssmenu.appendChild(italic);
	var under = document.createElement("Button");
        under.class = "editPanel";
	    under.className = "tags btn";
        under.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/metro-design/512/underlined_font-16.png")';
	cssmenu.appendChild(under);
	var through = document.createElement("Button");
        through.class = "editPanel";
	    through.className = "tags btn";
        through.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/iconano-text-editor/512/171-S-16.png")';
	cssmenu.appendChild(through);
	var alignLeft = document.createElement("Button");
        alignLeft.class = "editPanel";
	    alignLeft.className = "tags btn";
        alignLeft.style.backgroundImage = 'url("https://cdn2.iconfinder.com/data/icons/inverticons-stroke-vol-4/32/text_align_left-16.png")';
	cssmenu.appendChild(alignLeft);
	var alignCenter = document.createElement("Button");
        alignCenter.class = "editPanel";
	    alignCenter.className = "tags btn";
        alignCenter.style.backgroundImage = 'url("https://cdn2.iconfinder.com/data/icons/inverticons-stroke-vol-4/32/text_align_center-16.png")';
	cssmenu.appendChild(alignCenter);
	var alignRight = document.createElement("Button");
        alignRight.class = "editPanel";
	    alignRight.className = "tags btn";
        alignRight.style.backgroundImage = 'url("https://cdn2.iconfinder.com/data/icons/inverticons-stroke-vol-4/32/text_align_right-16.png")';
	cssmenu.appendChild(alignRight);
	var txtcolor = document.createElement("Label");
        txtcolor.class = "editPanel";
	    txtcolor.className = "tags inputs ";
        txtcolor.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/essentials-volume-6/128/color-wheel-16.png")';
		var picker = document.createElement("Input");
		    picker.class ="editPanel";
			picker.type ="color";
			picker.className = "color";
		txtcolor.appendChild(picker);
	cssmenu.appendChild(txtcolor);
		var letSpacing = document.createElement("select");
        letSpacing.class = "editPanel";
	    letSpacing.className = "tags";
        letSpacing.style.backgroundImage = 'url("https://cdn4.iconfinder.com/data/icons/transform-edit/100/transform-text-kerning-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    letSpacing.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="8";
	    letSpacing.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="10";
	    letSpacing.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="12";
	    letSpacing.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="16";
	    letSpacing.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="32";
	    letSpacing.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="64";
	    letSpacing.appendChild(op6);
    cssmenu.appendChild(letSpacing);
		var wordSpacing = document.createElement("select");
        wordSpacing.class = "editPanel";
	    wordSpacing.className = "tags";
        wordSpacing.style.backgroundImage = 'url("https://cdn3.iconfinder.com/data/icons/jellycons-outline-text-formatting-vol-1/64/062-Set_Line_Spacing-font_align_text_edit_type_content_format-16.png")';
	      var op = document.createElement("option");
	          op.text ="";
	    wordSpacing.appendChild(op);
	      var op1 = document.createElement("option");
	          op1.text ="8";
	    wordSpacing.appendChild(op1);
	      var op2 = document.createElement("option");
	          op2.text ="10";
	    wordSpacing.appendChild(op2);
	      var op3 = document.createElement("option");
	          op3.text ="12";
	    wordSpacing.appendChild(op3);
	      var op4 = document.createElement("option");
	          op4.text ="16";
	    wordSpacing.appendChild(op4);
	      var op5 = document.createElement("option");
	          op5.text ="32";
	    wordSpacing.appendChild(op5);
	      var op6 = document.createElement("option");
	          op6.text ="64";
	    wordSpacing.appendChild(op6);
    cssmenu.appendChild(wordSpacing);
	 mainBG.appendChild(cssmenu);
	 document.body.appendChild(mainBG);
	











//functions




	
}